In [1]:
import numpy as np
import random

#### 1. Write a Python Program to find sum of array?

In [2]:
arr = np.array(random.sample(range(1, 30), 10))
arr

array([26, 23, 14,  1,  7, 21, 29, 10, 27, 13])

In [3]:
arr.sum()

171

In [4]:
total_sum = 0
for i in arr:
    total_sum +=i
else:
    print("sum of array elements :-",total_sum)

sum of array elements :- 171


#### 2. Write a Python Program to find largest element in an array?

In [5]:
arr.max()

29

In [6]:
max_value = 0
for i in arr:
    if max_value < i:
        max_value = i
else:
    print("max value in array is ",max_value)

max value in array is  29


#### 3. Write a Python Program for array rotation?

In [7]:
arr[::-1]

array([13, 27, 10, 29, 21,  7,  1, 14, 23, 26])

#### 4. Write a Python Program to Split the array and add the first part to the end?

In [8]:
if(len(arr) %2 ==0):
    mid_value_index = len(arr)//2
else:
    mid_value_index = (len(arr)+1)//2

a1 = arr[:mid_value_index]
a2 = arr[mid_value_index:]

new_arr = np.hstack((a2,a1)) 
print(new_arr)

[21 29 10 27 13 26 23 14  1  7]


#### 5. Write a Python Program to check if given array is Monotonic?

#### Answer.
    An array is monotonic if it is either monotone increasing or monotone decreasing.
    i.e. 
    - monotone increasing means next consecutive elements must be greater or equal to the previous element
    - monotone decreasing means next consecutive elements must be smaller or equal to the previous element    

In [9]:
def check_monotonic(arr):
    status = (all(arr[i] <= arr[i + 1] for i in range(len(arr) - 1)) or all(arr[i] >= arr[i + 1] for i in range(len(arr) - 1)))
    return "Monotonic" if status else "Non-Monotonic"

In [10]:
# print(f"The given array {arr} is {'Monotonic' if check_monotonic(arr) else 'Non-Monotonic'}")
print(f"The given array {arr} is {check_monotonic(arr)}")

The given array [26 23 14  1  7 21 29 10 27 13] is Non-Monotonic


In [11]:
arr = [2,2,7,8,9,9]
print(f"The given array {arr} is {check_monotonic(arr)}")

The given array [2, 2, 7, 8, 9, 9] is Monotonic
